datadir="data"
logdir="optuna_runs"
num_layers=3
hidden_dim=128
edge_embedding_dim=128
ffn_hidden_dim=80
n_heads=4
max_in_degree=5
max_out_degree=5
max_path_distance=5
test_size=0.8
batch_size=128
lr=2.5e-3
min_b1=0.7
max_b1=0.99
min_b2=0.99
max_b2=0.9999
min_weight_decay=0.0
max_weight_decay=0.1
min_eps=1e-10
max_eps=1e-7
min_momentum=0.0
max_momentum=1.0
min_dampening=0.0
max_dampening=1.0
min_clip_grad_norm=1.0
max_clip_grad_norm=7.0
torch_device="cuda"
epochs=20
min_lr_power=0.1
max_lr_power=0.9
min_lr_patience=0
max_lr_patience=5
min_lr_cooldown=0
max_lr_cooldown=3
min_lr_min=1e-7
max_lr_min=3e-5
min_lr_max=1e-4
max_lr_max=1e-2
min_lr_warmup=0
max_lr_warmup=3
min_lr_window=1
max_lr_window=5
min_lr_reset=0
max_lr_reset=7
min_lr_factor=0.1
max_lr_factor=0.9
study_name="default_study"
accumulation_steps=4
checkpoint_dir="optuna_models"
min_dropout=0.0
max_dropout=0.5
tune_size=0.25
norm_type="layer"
